# .gitpod.yml
tasks:
  - init: pip install -r requirements.txt
    command: python app.py

ports:
  - port: 3000
    onOpen: open-browser
    visibility: public

vscode:
  extensions:
    - ms-python.python
